version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/questionnaire
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: library/postgres:11.10-alpine
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=questionnaire

#services:
#  postgres:
#    image: library/postgres:11.10-alpine
#    ports:
#      - 5432:5432
#    environment:
#      - POSTGRES_USER=test
#      - POSTGRES_PASSWORD=test
#      - POSTGRES_DB=questionnaire
